### ISSUE TITLE
Populate actions chart is unsafe (or something)

### ISSUE THREAD

**Issue by benjitobias** [benjitobias/working_bizint_ng#4]
```bizint_web  | Internal Server Error: /populate-actions-chart/
bizint_web  | Traceback (most recent call last):
bizint_web  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
bizint_web  |     response = get_response(request)
bizint_web  |                ^^^^^^^^^^^^^^^^^^^^^
bizint_web  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 179, in _get_response
bizint_web  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
bizint_web  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bizint_web  |   File "/app/counter/views.py", line 110, in populate_actions_chart
bizint_web  |     return JsonResponse(data=data)
bizint_web  |            ^^^^^^^^^^^^^^^^^^^^^^^
bizint_web  |   File "/usr/local/lib/python3.11/site-packages/django/http/response.py", line 560, in __init__
bizint_web  |     raise TypeError(
bizint_web  | TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
bizint_web  | [26/Apr/2024 22:45:25] "GET /populate-actions-chart/ HTTP/1.1" 500 63575
```

**Comment by benjitobias** [comment]
This seems to only be an issue if returning empty data. I haven't properly researched it but I couldn't recreate it when there was data loaded into the DB and it sort of makes self (NoneType is non-dict object)
